name: 'Terratest GitHub Actions'
on:
  pull_request:
    branches:
      - master
    types: [labeled]
  workflow_dispatch:
  
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@master
        
      # Login to Azure with Credentials
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

        
        # Environments
        env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              
#       - name: Download Go Modules
#         working-directory: _test
#         run: go mod tidy
      
      - name:  Install Terratest
        working-directory: _test
        run: go install github.com/gruntwork-io/terratest/modules/terraform
      
      
      - name: 'Terratest public-private-subnet'
#         if: ${{ github.event.label.name == 'terratest' }}
        uses: 'clouddrove/github-actions@v9.0.2'
        with:
          actions_subcommand: 'terratest'
          tf_actions_working_dir: '_test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()
